### ISSUE TITLE
Compilation error in file lib/ash_authentication/strategies/github.ex

### ISSUE THREAD

**Issue by puruzio** [team-alembic/ash_authentication#289]
While upgrading to 3.11, I received the following error:
```
== Compilation error in file lib/ash_authentication/strategies/github.ex ==
** (UndefinedFunctionError) function Code.Identifier.inspect_as_key/1 is undefined or private
    (elixir 1.14.1) Code.Identifier.inspect_as_key(:scope)
    (elixir 1.14.1) inspect_overrides/1_6.ex:95: Inspect.List.keyword/2
    (elixir 1.14.1) lib/inspect/algebra.ex:472: Inspect.Algebra.container_each/6
    (elixir 1.14.1) lib/inspect/algebra.ex:449: Inspect.Algebra.container_doc/6
    (elixir 1.14.1) lib/kernel.ex:2254: Kernel.inspect/2
    lib/ash_authentication/strategies/github/dsl.ex:46: anonymous fn/1 in AshAuthentication.Strategy.Github.Dsl.strategy_override_docs/1
    (elixir 1.14.1) lib/enum.ex:1755: anonymous fn/2 in Enum.map_join/3
    (elixir 1.14.1) lib/enum.ex:4292: Enum.map_intersperse_list/3
could not compile dependency :ash_authentication, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ash_authentication", update it with "mix deps.update ash_authentication" or clean it with "mix deps.clean ash_authentication"
```
I'm on Windows 11 and Elixir 1.14.

**Comment by jimsynz** [comment]
You fixed it?

**Comment by puruzio** [comment]
Cleaning and reinstalling all dependencies somehow fixed it :) Thanks!
