### ISSUE TITLE
MyApp.Secrets must implement the 'AshAuthentication.Secret` behaviour.

### ISSUE THREAD

**Issue by puruzio** [team-alembic/ash_authentication#293]
I followed the example here (https://ash-hq.org/docs/guides/ash_authentication/latest/github-quickstart) but ran into this error. It talks about `password_reset` which I'm not sure where it's coming from.
```
** (EXIT from #PID<0.104.0>) an exception was raised:
    ** (Spark.Error.DslError) [nil]
 password_reset:
  `MyApp.Secrets` must implement the `AshAuthentication.Secret` behaviour.
        lib/MyApp/accounts/resources/user.ex:1: anonymous fn/1 in MyApp.Accounts.User.__verify_ash_dsl__/1
        (elixir 1.14.1) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
        lib/MyApp/accounts/resources/user.ex:1: MyApp.Accounts.User.__verify_ash_dsl__/1
        (elixir 1.14.1) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
        (elixir 1.14.1) lib/module/parallel_checker.ex:239: Module.ParallelChecker.check_module/2
        (elixir 1.14.1) lib/module/parallel_checker.ex:78: anonymous fn/5 in Module.ParallelChecker.spawn/3
```

**Comment by puruzio** [comment]
Sorry, it was an error on my side, typo in the module name :(
