### ISSUE TITLE
The action `:confirm_change` should have the `:require_atomic?` option set to `false

### ISSUE THREAD

**Issue by dan-klasson** [team-alembic/ash_authentication#740]
Following the [Confirmation Tutorial](https://ash-hq.org/docs/guides/ash_authentication/latest/tutorials/confirmation) I get:

```
** (Spark.Error.DslError) [Potion.Accounts.User]
 actions -> confirm_change -> require_atomic?:
  The action `:confirm_change` should have the `:require_atomic?` option set to `false`
    (elixir 1.16.3) lib/process.ex:860: Process.info/2
    (spark 2.1.22) lib/spark/error/dsl_error.ex:30: Spark.Error.DslError.exception/1
    (ash_authentication 4.0.0) lib/ash_authentication/validations/action.ex:231: AshAuthentication.Validations.Action.validate_action_option/3
    (ash_authentication 4.0.0) lib/ash_authentication/add_ons/confirmation/transformer.ex:158: AshAuthentication.AddOn.Confirmation.Transformer.validate_confirm_action/2
    (ash_authentication 4.0.0) lib/ash_authentication/add_ons/confirmation/transformer.ex:34: AshAuthentication.AddOn.Confirmation.Transformer.transform/2
    (ash_authentication 4.0.0) lib/ash_authentication/strategies/custom/transformer.ex:109: AshAuthentication.Strategy.Custom.Transformer.do_transform/3
    (ash_authentication 4.0.0) lib/ash_authentication/strategies/custom/transformer.ex:55: anonymous fn/2 in AshAuthentication.Strategy.Custom.Transformer.do_add_on_transforms/1
    (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
    (elixir 1.16.3) lib/enum.ex:2582: Enum.reduce_while/3
    (spark 2.1.22) lib/spark/dsl/extension.ex:590: anonymous fn/4 in Spark.Dsl.Extension.run_transformers/4
    (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
    (elixir 1.16.3) lib/enum.ex:2582: Enum.reduce_while/3
    /Users/danielklasson/Code/potion/lib/potion/accounts/resources/user.ex:1: (file)
    (stdlib 5.2.3) erl_eval.erl:750: :erl_eval.do_apply/7
    (stdlib 5.2.3) erl_eval.erl:1026: :erl_eval.expr_list/7
    (stdlib 5.2.3) erl_eval.erl:456: :erl_eval.expr/6
    (stdlib 5.2.3) erl_eval.erl:1026: :erl_eval.expr_list/7
    (stdlib 5.2.3) erl_eval.erl:456: :erl_eval.expr/6
    (stdlib 5.2.3) erl_eval.erl:136: :erl_eval.exprs/6
```

Adding `:require_atomic?` to `:confirm_change` like this:

```  
actions do
    update :confirm_change do
      argument :confirm, :string, allow_nil?: false, public?: true

      change AshAuthentication.AddOn.Confirmation.ConfirmChange
      change AshAuthentication.GenerateTokenChange
       require_atomic? false
      # change MyApp.UpdateCrmSystem, only_when_valid?: true
    end
  end
```

I get this error instead:

```
** (RuntimeError) Exception in transformer AshAuthentication.Strategy.Custom.Transformer on Potion.Accounts.User: 

protocol Enumerable not implemented for nil of type Atom
    (elixir 1.16.3) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.16.3) lib/enum.ex:166: Enumerable.reduce/3
    (elixir 1.16.3) lib/enum.ex:4396: Enum.reverse/1
    (elixir 1.16.3) lib/enum.ex:3728: Enum.to_list/1
    (elixir 1.16.3) lib/map_set.ex:97: MapSet.new/1
    (ash_authentication 4.0.0) lib/ash_authentication/add_ons/confirmation/transformer.ex:159: AshAuthentication.AddOn.Confirmation.Transformer.validate_confirm_action/2
    (ash_authentication 4.0.0) lib/ash_authentication/add_ons/confirmation/transformer.ex:34: AshAuthentication.AddOn.Confirmation.Transformer.transform/2
    (ash_authentication 4.0.0) lib/ash_authentication/strategies/custom/transformer.ex:109: AshAuthentication.Strategy.Custom.Transformer.do_transform/3
    (ash_authentication 4.0.0) lib/ash_authentication/strategies/custom/transformer.ex:55: anonymous fn/2 in AshAuthentication.Strategy.Custom.Transformer.do_add_on_transforms/1
    (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
    (elixir 1.16.3) lib/enum.ex:2582: Enum.reduce_while/3
    (spark 2.1.22) lib/spark/dsl/extension.ex:590: anonymous fn/4 in Spark.Dsl.Extension.run_transformers/4
    (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
    (elixir 1.16.3) lib/enum.ex:2582: Enum.reduce_while/3
    /Users/danielklasson/Code/potion/lib/potion/accounts/resources/user.ex:1: (file)
    (stdlib 5.2.3) erl_eval.erl:750: :erl_eval.do_apply/7
    (stdlib 5.2.3) erl_eval.erl:1026: :erl_eval.expr_list/7
    (stdlib 5.2.3) erl_eval.erl:456: :erl_eval.expr/6
    (stdlib 5.2.3) erl_eval.erl:1026: :erl_eval.expr_list/7
```

**Comment by zachdaniel** [comment]
Hey @dan-klasson can you try `main`? `{:ash_authentication, github: "team-alembic/ash_authentication", override: true}`.

**Comment by dan-klasson** [comment]
> Hey @dan-klasson can you try `main`? `{:ash_authentication, github: "team-alembic/ash_authentication", override: true}`.

Then I get this with `:require_atomic? false`:

```
== Compilation error in file lib/potion/accounts/resources/user.ex ==
** (Spark.Error.DslError) [Potion.Accounts.User]
actions -> confirm_change -> accept:
  The confirmation action must accept the monitored fields.
    (elixir 1.16.3) lib/process.ex:860: Process.info/2
    (spark 2.2.7) lib/spark/error/dsl_error.ex:30: Spark.Error.DslError.exception/1
    (ash_authentication 4.0.1) lib/ash_authentication/add_ons/confirmation/transformer.ex:171: AshAuthentication.AddOn.Confirmation.Transformer.validate_confirm_action/2
    (ash_authentication 4.0.1) lib/ash_authentication/add_ons/confirmation/transformer.ex:34: AshAuthentication.AddOn.Confirmation.Transformer.transform/2
    (ash_authentication 4.0.1) lib/ash_authentication/strategies/custom/transformer.ex:109: AshAuthentication.Strategy.Custom.Transformer.do_transform/3
    (ash_authentication 4.0.1) lib/ash_authentication/strategies/custom/transformer.ex:55: anonymous fn/2 in AshAuthentication.Strategy.Custom.Transformer.do_add_on_transforms/1
    (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
    /Users/danielklasson/Code/potion/lib/potion/accounts/resources/user.ex:1: (file)
```

**Comment by zachdaniel** [comment]
```elixir
actions do
    update :confirm_change do
      argument :confirm, :string, allow_nil?: false, public?: true
      accept [:the, :fields] # typically just `:email` here

      change AshAuthentication.AddOn.Confirmation.ConfirmChange
      change AshAuthentication.GenerateTokenChange
       require_atomic? false
      # change MyApp.UpdateCrmSystem, only_when_valid?: true
    end
  end
```

**Comment by dan-klasson** [comment]
After adding `import Swoosh.Email` to both my sender modules and changing `@token` to `token` I now get this error:

```
Compiling 27 files (.ex)
** (EXIT from #PID<0.98.0>) an exception was raised:
    ** (Spark.Error.DslError) identities -> unique_email:
  Identity unique_email is declared with `eager_check_with` or `pre_check_with` but the resource has no primary read action.
        lib/potion/accounts/resources/user.ex:1: anonymous fn/1 in Potion.Accounts.User.__verify_spark_dsl__/1
        (elixir 1.16.3) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
        lib/potion/accounts/resources/user.ex:1: Potion.Accounts.User.__verify_spark_dsl__/1
        (elixir 1.16.3) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
        (elixir 1.16.3) lib/module/parallel_checker.ex:271: Module.ParallelChecker.check_module/3
        (elixir 1.16.3) lib/module/parallel_checker.ex:82: anonymous fn/6 in Module.ParallelChecker.spawn/4
```

In my `user.ex` resource I have this:

```
  identities do
    identity :unique_email, [:email]  do
      eager_check_with Potion.Accounts
    end
  end
```

**Comment by zachdaniel** [comment]
Add
```elixir
actions do
  defaults [:read] # <- add this to your actions block of your resource.
end
```

**Comment by zachdaniel** [comment]
I think the issues here have been resolved, will close, but feel free to reopen 🙇

**Comment by dan-klasson** [comment]
Resolved in https://github.com/team-alembic/ash_authentication/pull/741
