### ISSUE TITLE
Confusing debug message printed when clicking on an expired magic link

### ISSUE THREAD

**Issue by sevenseacat** [team-alembic/ash_authentication#840]
With authentication debugging turned on:

```
[debug] Processing with AshAuthentication.Phoenix.StrategyRouter
  Parameters: %{"token" => "<an expired token>"}
  Pipelines: [:browser]
[debug] Claim %{"exp" => 1731480889} did not pass validation.

Current time: 1731481917

[debug] QUERY OK db=0.2ms idle=1612.1ms
begin []
↳ anonymous fn/4 in Ash.Changeset.with_hooks/3, at: lib/ash/changeset/changeset.ex:3493
[debug] QUERY OK db=0.9ms
rollback []
↳ anonymous fn/4 in Ash.Changeset.with_hooks/3, at: lib/ash/changeset/changeset.ex:3493
[warning] Authentication failed:
Bread Crumbs:
  > Error returned from: Tunez.Accounts.User.sign_in_with_magic_link

Invalid Error

* attribute email is required
  (ash 3.4.41) lib/ash/error/changes/required.ex:4: Ash.Error.Changes.Required.exception/1
  (ash 3.4.41) lib/ash/changeset/changeset.ex:3337: Ash.Changeset.add_required_attribute_error/2
  (elixir 1.17.3) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
  (ash 3.4.41) lib/ash/actions/create/create.ex:350: anonymous fn/6 in Ash.Actions.Create.commit/3
  (ash 3.4.41) lib/ash/changeset/changeset.ex:3962: Ash.Changeset.run_around_actions/2
  (ash 3.4.41) lib/ash/changeset/changeset.ex:3495: anonymous fn/3 in Ash.Changeset.with_hooks/3
  (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1400: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
  (db_connection 2.7.0) lib/db_connection.ex:1756: DBConnection.run_transaction/4
  (ash 3.4.41) lib/ash/changeset/changeset.ex:3493: anonymous fn/4 in Ash.Changeset.with_hooks/3
  (ash 3.4.41) lib/ash/changeset/changeset.ex:3640: anonymous fn/2 in Ash.Changeset.transaction_hooks/2
  (ash 3.4.41) lib/ash/changeset/changeset.ex:3468: Ash.Changeset.with_hooks/3
  (ash 3.4.41) lib/ash/actions/create/create.ex:260: Ash.Actions.Create.commit/3
  (ash 3.4.41) lib/ash/actions/create/create.ex:132: Ash.Actions.Create.do_run/4
  (ash 3.4.41) lib/ash/actions/create/create.ex:50: Ash.Actions.Create.run/4
  (ash_authentication 4.3.0) lib/ash_authentication/strategies/magic_link/actions.ex:62: AshAuthentication.Strategy.MagicLink.Actions.sign_in/3
  (ash_authentication 4.3.0) lib/ash_authentication/strategies/magic_link/plug.ex:44: AshAuthentication.Strategy.MagicLink.Plug.sign_in/2
  (ash_authentication 4.3.0) lib/ash_authentication/plug/dispatcher.ex:29: AshAuthentication.Plug.Dispatcher.call/2
  ...
```

The debug message prints what the problem really is (an expired token) but the debug warning is something else entirely! It's like its still trying to create a User record? Not sure what is going on there...

**Comment by mburuwarui** [comment]
Also when initializing a new Ash Phoenix project with mix igniter.new and AshAuthentication, the magic link strategy fails due to a required email attribute not being populated during user sign-in.

❯ mix igniter.new myapp \
      --with phx.new \
      --install ash,ash_postgres,ash_graphql \
      --install ash_authentication_phoenix \
      --auth-strategy magic_link

```
[debug] Replied in 493ms
[info] GET /auth/user/magic_link/
[debug] Processing with AshAuthentication.Phoenix.StrategyRouter
  Parameters: %{"token" => "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3QiOiJzaWduX2luX3dpdGhfbW"}
  Pipelines: [:browser]
[warning] Authentication failed: 
Bread Crumbs:
  > Error returned from: Subukia.Accounts.User.sign_in_with_magic_link

Invalid Error

* attribute email is required
  (ash 3.4.42) lib/ash/error/changes/required.ex:4: Ash.Error.Changes.Required.exception/1
  (ash 3.4.42) lib/ash/changeset/changeset.ex:3337: Ash.Changeset.add_required_attribute_error/2
  (elixir 1.17.3) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
  (ash 3.4.42) lib/ash/actions/create/create.ex:350: anonymous fn/6 in Ash.Actions.Create.commit/3
  (ash 3.4.42) lib/ash/changeset/changeset.ex:3962: Ash.Changeset.run_around_actions/2
  (ash 3.4.42) lib/ash/changeset/changeset.ex:3640: anonymous fn/2 in Ash.Changeset.transaction_hooks/2
  (ash 3.4.42) lib/ash/changeset/changeset.ex:3550: Ash.Changeset.with_hooks/3
  (ash 3.4.42) lib/ash/actions/create/create.ex:260: Ash.Actions.Create.commit/3
  (ash 3.4.42) lib/ash/actions/create/create.ex:132: Ash.Actions.Create.do_run/4
  (ash 3.4.42) lib/ash/actions/create/create.ex:50: Ash.Actions.Create.run/4
  (ash_authentication 4.3.3) lib/ash_authentication/strategies/magic_link/actions.ex:62: AshAuthentication.Strategy.M
agicLink.Actions.sign_in/3
  (ash_authentication 4.3.3) lib/ash_authentication/strategies/magic_link/plug.ex:44: AshAuthentication.Strategy.Magi
cLink.Plug.sign_in/2
  (ash_authentication 4.3.3) lib/ash_authentication/plug/dispatcher.ex:29: AshAuthentication.Plug.Dispatcher.call/2
. . .
```
